source 'https://rubygems.org'
ruby '2.1.2'

gem 'rails', '4.1.1'
gem 'pg', '~> 0.17.1'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
# gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails', '~> 3.1.2'
# gem 'turbolinks'
# gem 'jbuilder', '~> 2.0'
# gem 'sdoc', '~> 0.4.0',   group: :doc
gem 'spring', '~> 1.1.3',   group: :development
# gem 'bcrypt', '~> 3.1.7'
# gem 'unicorn'
# gem 'capistrano-rails', group: :development
# Use debugger

gem 'activeadmin', github: 'gregbell/active_admin' # Until it's 1.0.0.0
gem 'devise', '~> 3.3.0'

group :development do
  gem 'better_errors', '~> 2.0.0'
  gem 'meta_request', '~> 0.3.4'
  gem 'quiet_assets', '~> 1.0.3'
end

group :development, :test do
  gem 'capybara', '~> 2.4.1'
  gem 'capybara-screenshot', '~> 0.3.22'
  gem 'database_cleaner', '~> 1.3.0'
  gem 'factory_girl_rails', '~> 4.4.1'
  gem 'faker', '~> 1.4.3'
  gem 'poltergeist', '~> 1.5.1'
  gem 'pry-nav', '~> 0.2.4'
  gem 'pry-rails', '~> 0.3.2'
  gem 'pry-stack_explorer', '~> 0.4.9.1'
  gem 'pry-theme', '~> 1.1.3'
  gem 'rspec-rails', '~> 3.1.0'
  gem 'rubocop', '~> 0.26.0'
  gem 'shoulda-matchers', '~> 2.7.0'
  gem 'spring-commands-rspec', '~> 1.0.2'
end
